#!/bin/bash

echo "🧪 Testing Fresh User Account Data Isolation"
echo "============================================"
echo ""
echo "Steps to verify the fix:"
echo ""
echo "1. ❌ IMPORTANT: Uninstall the app from simulator completely"
echo "   - This clears ALL UserDefaults data"
echo ""
echo "2. 🏗️  Rebuild and install the app fresh"
echo ""
echo "3. 👤 Create a BRAND NEW Firebase account"
echo "   - Use a completely new email you haven't used before"
echo "   - Example: test+$(date +%s)@example.com"
echo ""
echo "4. ✅ Verify empty state:"
echo "   - Weight tab should show NO history"
echo "   - Fasting should be stopped with default 16h goal"
echo "   - Goals should be default (2000 cal)"
echo ""
echo "5. 📝 Add test data:"
echo "   - Add weight entry: 75kg"
echo "   - Start fasting timer"
echo "   - Change caloric goal to 2500"
echo ""
echo "6. 🚪 Log out and create ANOTHER new account"
echo ""
echo "7. ✅ Verify isolation:"
echo "   - New user should see ZERO weight history"
echo "   - New user should see NO active fast"
echo "   - New user should see default 2000 cal goal"
echo ""
echo "If you see the old data (100kg, 80kg), that means:"
echo "  - The data is cached in Firebase for THAT user account"
echo "  - You need to use a different email address"
echo "  - OR delete the user's data from Firebase Console"
echo ""
