"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteCleansedFood = exports.exportCleansedFoods = exports.getCleansedFoods = exports.analyzeAndCleanFoods = exports.getAllFoods = exports.getNutrientSuggestions = exports.importGenericFoods = exports.extractIngredientsWithAI = exports.analyzeAdditivesEnhanced = exports.getContextualNutritionScore = exports.getPremiumOverrideStatus = exports.setPremiumOverride = exports.bulkAddToMailchimp = exports.getAuthenticatedEmails = exports.getUserAnalytics = exports.deleteUsers = exports.updateUser = exports.addUser = exports.getUsers = exports.checkGA4Config = exports.getGA4Analytics = exports.getWebsiteAnalytics = exports.getAnalyticsData = exports.getOverviewStats = exports.uploadMasterDatabase = exports.updateAlgoliaIndex = exports.deleteFromIndex = exports.getBrowseJobData = exports.browseAllIndices = exports.adminSaveFood = exports.searchTescoAndUpdate = exports.updateServingSizes = exports.fixExistingFoodsVerification = exports.resetAllFoodsToInitial = exports.resetAdminManualFoods = exports.moveFoodsBetweenIndices = exports.moveFoodBetweenCollections = exports.deleteFoodComprehensive = exports.deleteFoodFromAlgolia = exports.deleteVerifiedFoods = exports.updateVerifiedFood = exports.addVerifiedFood = exports.searchFoodsByCollection = exports.getFoodDetails = exports.searchFoodsWeb = exports.fastSearchFoods = exports.searchFoodByBarcode = exports.searchCleansedFoods = exports.searchFoods = exports.addVerifiedFoodComplete = void 0;
exports.getGenericDatabaseStats = exports.importMcCanceWiddowson = exports.getEnhancementStats = exports.enhanceGenericFoods = exports.getAlgoliaIndexStats = exports.syncAlgoliaToFirebase = exports.checkAlgoliaFirebaseSync = exports.syncNewDatabasesToAlgolia = exports.configureAlgoliaIndices = exports.searchFoodsAlgolia = exports.bulkImportFoodsToAlgolia = exports.syncUKFoodsCleanedToAlgolia = exports.syncTescoProductToAlgolia = exports.syncAIManuallyAddedFoodToAlgolia = exports.syncAIEnhancedFoodToAlgolia = exports.syncUserAddedFoodToAlgolia = exports.syncManualFoodToAlgolia = exports.syncFoodToAlgolia = exports.syncVerifiedFoodToAlgolia = exports.deleteSpecificItem = exports.searchGenericOliveOil = exports.deleteGenericFoods = exports.inferMealIngredients = exports.scanProductComplete = exports.recognizeFood = exports.auditMissingIngredients = exports.findIngredients = exports.parseIngredientsOCRCached = exports.parseIngredientsOCR = exports.parseNutritionOCRCached = exports.parseNutritionOCR = exports.parseAdditivesWithAICached = exports.parseAdditivesWithAI = exports.parseMicronutrientsWithAICached = exports.parseMicronutrientsWithAI = exports.getFood = exports.batchSaveFoods = exports.deleteFood = exports.saveFood = exports.deleteUserReport = exports.updateUserReport = exports.getUserReports = exports.notifyIncompleteFood = exports.standardizeIngredients = exports.replaceAllFoods = exports.detectLiveText = exports.testCors = exports.updateCleansedFoodStatus = exports.emergencyCleanCleansedFoods = exports.updateCleansedFood = void 0;
exports.validateFoodsFromDatabase = exports.batchSaveFoodCategories = exports.fixFoodServingSizes = exports.fixCustomCategoryServingSizes = exports.resetCategorizationProgress = exports.getCategorizationProgress = exports.getFoodsForCategorization = exports.getCategories = exports.updateFoodCategory = exports.getCategorizeStats = exports.categorizeFoodsFromDatabase = exports.categorizeFoods = exports.cleanupTescoDatabase = exports.scheduledTescoBuild = exports.syncTescoToAlgolia = exports.configureTescoAlgoliaIndex = exports.getTescoDatabaseStats = exports.resetTescoDatabase = exports.stopTescoBuild = exports.pauseTescoBuild = exports.startTescoBuild = exports.getTescoBuildProgress = exports.lookupTescoProduct = exports.extractWithPuppeteer = exports.extractUKProductData = exports.generateManualSearchLinks = exports.discoverUKProductPage = exports.rescanProducts = exports.fixHtmlCode = exports.fixSimpleIngredients = exports.fixKjKcalCombinedCalories = exports.batchUpdateFoodsWithFirebase = exports.batchUpdateFoods = exports.scanDatabaseIssues = exports.syncAllEmailConsentsToMailchimp = exports.syncEmailConsentToMailchimp = exports.clearQueryRules = exports.getQueryRulesStats = exports.configureQueryRules = exports.clearSynonymsFromAlgolia = exports.getSynonymStats = exports.syncSynonymsToAlgolia = exports.consolidateConsumerFoods = exports.clearConsumerFoods = exports.syncConsumerFoodsToAlgolia = exports.getConsumerFoodsStats = exports.importConsumerFoods = exports.clearGenericDatabase = exports.cleanupGenericDatabase = exports.syncGenericDatabaseToAlgolia = void 0;
exports.cleanupOldFoodUpdates = exports.getSyncStats = exports.initializeDatabaseVersion = exports.recordFoodUpdate = exports.getFoodDatabaseDelta = exports.getCurrentDatabaseVersion = exports.getMasterDatabaseStats = exports.syncMasterDatabaseToAlgolia = exports.clearAlgoliaIndex = exports.syncTescoImageQuality = exports.getTescoImageStats = exports.filterTescoImages = exports.updateFoodNutrition = exports.batchUploadFoodImages = exports.uploadFoodImage = exports.clearMarkedForDeletion = exports.unmarkForDeletion = exports.deleteMarkedItems = exports.getMarkedForDeletion = exports.getFoodsForValidation = exports.resetValidationProgress = exports.getValidationProgress = exports.getValidationStats = void 0;
const admin = require("firebase-admin");
// Initialize Firebase Admin
if (!admin.apps.length) {
    admin.initializeApp();
}
// Export the essential functions
var efficient_import_1 = require("./efficient-import");
Object.defineProperty(exports, "addVerifiedFoodComplete", { enumerable: true, get: function () { return efficient_import_1.addVerifiedFoodComplete; } });
var search_foods_1 = require("./search-foods");
Object.defineProperty(exports, "searchFoods", { enumerable: true, get: function () { return search_foods_1.searchFoods; } });
var search_cleansed_foods_1 = require("./search-cleansed-foods");
Object.defineProperty(exports, "searchCleansedFoods", { enumerable: true, get: function () { return search_cleansed_foods_1.searchCleansedFoods; } });
var search_food_by_barcode_1 = require("./search-food-by-barcode");
Object.defineProperty(exports, "searchFoodByBarcode", { enumerable: true, get: function () { return search_food_by_barcode_1.searchFoodByBarcode; } });
var fast_search_1 = require("./fast-search");
Object.defineProperty(exports, "fastSearchFoods", { enumerable: true, get: function () { return fast_search_1.fastSearchFoods; } });
var search_foods_web_1 = require("./search-foods-web");
Object.defineProperty(exports, "searchFoodsWeb", { enumerable: true, get: function () { return search_foods_web_1.searchFoodsWeb; } });
var food_details_1 = require("./food-details");
Object.defineProperty(exports, "getFoodDetails", { enumerable: true, get: function () { return food_details_1.getFoodDetails; } });
var search_foods_by_collection_1 = require("./search-foods-by-collection");
Object.defineProperty(exports, "searchFoodsByCollection", { enumerable: true, get: function () { return search_foods_by_collection_1.searchFoodsByCollection; } });
var food_management_1 = require("./food-management");
Object.defineProperty(exports, "addVerifiedFood", { enumerable: true, get: function () { return food_management_1.addVerifiedFood; } });
Object.defineProperty(exports, "updateVerifiedFood", { enumerable: true, get: function () { return food_management_1.updateVerifiedFood; } });
Object.defineProperty(exports, "deleteVerifiedFoods", { enumerable: true, get: function () { return food_management_1.deleteVerifiedFoods; } });
Object.defineProperty(exports, "deleteFoodFromAlgolia", { enumerable: true, get: function () { return food_management_1.deleteFoodFromAlgolia; } });
Object.defineProperty(exports, "deleteFoodComprehensive", { enumerable: true, get: function () { return food_management_1.deleteFoodComprehensive; } });
Object.defineProperty(exports, "moveFoodBetweenCollections", { enumerable: true, get: function () { return food_management_1.moveFoodBetweenCollections; } });
Object.defineProperty(exports, "moveFoodsBetweenIndices", { enumerable: true, get: function () { return food_management_1.moveFoodsBetweenIndices; } });
Object.defineProperty(exports, "resetAdminManualFoods", { enumerable: true, get: function () { return food_management_1.resetAdminManualFoods; } });
Object.defineProperty(exports, "resetAllFoodsToInitial", { enumerable: true, get: function () { return food_management_1.resetAllFoodsToInitial; } });
Object.defineProperty(exports, "fixExistingFoodsVerification", { enumerable: true, get: function () { return food_management_1.fixExistingFoodsVerification; } });
Object.defineProperty(exports, "updateServingSizes", { enumerable: true, get: function () { return food_management_1.updateServingSizes; } });
Object.defineProperty(exports, "searchTescoAndUpdate", { enumerable: true, get: function () { return food_management_1.searchTescoAndUpdate; } });
Object.defineProperty(exports, "adminSaveFood", { enumerable: true, get: function () { return food_management_1.adminSaveFood; } });
Object.defineProperty(exports, "browseAllIndices", { enumerable: true, get: function () { return food_management_1.browseAllIndices; } });
Object.defineProperty(exports, "getBrowseJobData", { enumerable: true, get: function () { return food_management_1.getBrowseJobData; } });
Object.defineProperty(exports, "deleteFromIndex", { enumerable: true, get: function () { return food_management_1.deleteFromIndex; } });
Object.defineProperty(exports, "updateAlgoliaIndex", { enumerable: true, get: function () { return food_management_1.updateAlgoliaIndex; } });
var upload_master_database_1 = require("./upload-master-database");
Object.defineProperty(exports, "uploadMasterDatabase", { enumerable: true, get: function () { return upload_master_database_1.uploadMasterDatabase; } });
var analytics_1 = require("./analytics");
Object.defineProperty(exports, "getOverviewStats", { enumerable: true, get: function () { return analytics_1.getOverviewStats; } });
Object.defineProperty(exports, "getAnalyticsData", { enumerable: true, get: function () { return analytics_1.getAnalyticsData; } });
var website_analytics_1 = require("./website-analytics");
Object.defineProperty(exports, "getWebsiteAnalytics", { enumerable: true, get: function () { return website_analytics_1.getWebsiteAnalytics; } });
var ga4_analytics_1 = require("./ga4-analytics");
Object.defineProperty(exports, "getGA4Analytics", { enumerable: true, get: function () { return ga4_analytics_1.getGA4Analytics; } });
Object.defineProperty(exports, "checkGA4Config", { enumerable: true, get: function () { return ga4_analytics_1.checkGA4Config; } });
var user_management_1 = require("./user-management");
Object.defineProperty(exports, "getUsers", { enumerable: true, get: function () { return user_management_1.getUsers; } });
Object.defineProperty(exports, "addUser", { enumerable: true, get: function () { return user_management_1.addUser; } });
Object.defineProperty(exports, "updateUser", { enumerable: true, get: function () { return user_management_1.updateUser; } });
Object.defineProperty(exports, "deleteUsers", { enumerable: true, get: function () { return user_management_1.deleteUsers; } });
Object.defineProperty(exports, "getUserAnalytics", { enumerable: true, get: function () { return user_management_1.getUserAnalytics; } });
Object.defineProperty(exports, "getAuthenticatedEmails", { enumerable: true, get: function () { return user_management_1.getAuthenticatedEmails; } });
Object.defineProperty(exports, "bulkAddToMailchimp", { enumerable: true, get: function () { return user_management_1.bulkAddToMailchimp; } });
Object.defineProperty(exports, "setPremiumOverride", { enumerable: true, get: function () { return user_management_1.setPremiumOverride; } });
Object.defineProperty(exports, "getPremiumOverrideStatus", { enumerable: true, get: function () { return user_management_1.getPremiumOverrideStatus; } });
var contextual_nutrition_1 = require("./contextual-nutrition");
Object.defineProperty(exports, "getContextualNutritionScore", { enumerable: true, get: function () { return contextual_nutrition_1.getContextualNutritionScore; } });
var additive_analyzer_enhanced_1 = require("./additive-analyzer-enhanced");
Object.defineProperty(exports, "analyzeAdditivesEnhanced", { enumerable: true, get: function () { return additive_analyzer_enhanced_1.analyzeAdditivesEnhanced; } });
var intelligent_ingredient_extractor_1 = require("./intelligent-ingredient-extractor");
Object.defineProperty(exports, "extractIngredientsWithAI", { enumerable: true, get: function () { return intelligent_ingredient_extractor_1.extractIngredientsWithAI; } });
var import_generic_foods_1 = require("./import-generic-foods");
Object.defineProperty(exports, "importGenericFoods", { enumerable: true, get: function () { return import_generic_foods_1.importGenericFoods; } });
Object.defineProperty(exports, "getNutrientSuggestions", { enumerable: true, get: function () { return import_generic_foods_1.getNutrientSuggestions; } });
var get_all_foods_1 = require("./get-all-foods");
Object.defineProperty(exports, "getAllFoods", { enumerable: true, get: function () { return get_all_foods_1.getAllFoods; } });
var ai_food_cleaner_1 = require("./ai-food-cleaner");
Object.defineProperty(exports, "analyzeAndCleanFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.analyzeAndCleanFoods; } });
Object.defineProperty(exports, "getCleansedFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.getCleansedFoods; } });
Object.defineProperty(exports, "exportCleansedFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.exportCleansedFoods; } });
Object.defineProperty(exports, "deleteCleansedFood", { enumerable: true, get: function () { return ai_food_cleaner_1.deleteCleansedFood; } });
Object.defineProperty(exports, "updateCleansedFood", { enumerable: true, get: function () { return ai_food_cleaner_1.updateCleansedFood; } });
Object.defineProperty(exports, "emergencyCleanCleansedFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.emergencyCleanCleansedFoods; } });
Object.defineProperty(exports, "updateCleansedFoodStatus", { enumerable: true, get: function () { return ai_food_cleaner_1.updateCleansedFoodStatus; } });
var test_cors_1 = require("./test-cors");
Object.defineProperty(exports, "testCors", { enumerable: true, get: function () { return test_cors_1.testCors; } });
var detect_live_text_1 = require("./detect-live-text");
Object.defineProperty(exports, "detectLiveText", { enumerable: true, get: function () { return detect_live_text_1.detectLiveText; } });
// export { processIngredientText } from './process-ingredient-text'; // Disabled - uses old SDK
var replace_foods_database_1 = require("./replace-foods-database");
Object.defineProperty(exports, "replaceAllFoods", { enumerable: true, get: function () { return replace_foods_database_1.replaceAllFoods; } });
var standardize_ingredients_1 = require("./standardize-ingredients");
Object.defineProperty(exports, "standardizeIngredients", { enumerable: true, get: function () { return standardize_ingredients_1.standardizeIngredients; } });
var notify_incomplete_food_1 = require("./notify-incomplete-food");
Object.defineProperty(exports, "notifyIncompleteFood", { enumerable: true, get: function () { return notify_incomplete_food_1.notifyIncompleteFood; } });
var user_reports_1 = require("./user-reports");
Object.defineProperty(exports, "getUserReports", { enumerable: true, get: function () { return user_reports_1.getUserReports; } });
Object.defineProperty(exports, "updateUserReport", { enumerable: true, get: function () { return user_reports_1.updateUserReport; } });
Object.defineProperty(exports, "deleteUserReport", { enumerable: true, get: function () { return user_reports_1.deleteUserReport; } });
var save_food_1 = require("./save-food");
Object.defineProperty(exports, "saveFood", { enumerable: true, get: function () { return save_food_1.saveFood; } });
Object.defineProperty(exports, "deleteFood", { enumerable: true, get: function () { return save_food_1.deleteFood; } });
Object.defineProperty(exports, "batchSaveFoods", { enumerable: true, get: function () { return save_food_1.batchSaveFoods; } });
Object.defineProperty(exports, "getFood", { enumerable: true, get: function () { return save_food_1.getFood; } });
var parse_micronutrients_ai_1 = require("./parse-micronutrients-ai");
Object.defineProperty(exports, "parseMicronutrientsWithAI", { enumerable: true, get: function () { return parse_micronutrients_ai_1.parseMicronutrientsWithAI; } });
Object.defineProperty(exports, "parseMicronutrientsWithAICached", { enumerable: true, get: function () { return parse_micronutrients_ai_1.parseMicronutrientsWithAICached; } });
var parse_additives_ai_1 = require("./parse-additives-ai");
Object.defineProperty(exports, "parseAdditivesWithAI", { enumerable: true, get: function () { return parse_additives_ai_1.parseAdditivesWithAI; } });
Object.defineProperty(exports, "parseAdditivesWithAICached", { enumerable: true, get: function () { return parse_additives_ai_1.parseAdditivesWithAICached; } });
var parse_nutrition_ocr_1 = require("./parse-nutrition-ocr");
Object.defineProperty(exports, "parseNutritionOCR", { enumerable: true, get: function () { return parse_nutrition_ocr_1.parseNutritionOCR; } });
Object.defineProperty(exports, "parseNutritionOCRCached", { enumerable: true, get: function () { return parse_nutrition_ocr_1.parseNutritionOCRCached; } });
var parse_ingredients_ocr_1 = require("./parse-ingredients-ocr");
Object.defineProperty(exports, "parseIngredientsOCR", { enumerable: true, get: function () { return parse_ingredients_ocr_1.parseIngredientsOCR; } });
Object.defineProperty(exports, "parseIngredientsOCRCached", { enumerable: true, get: function () { return parse_ingredients_ocr_1.parseIngredientsOCRCached; } });
var find_ingredients_1 = require("./find-ingredients");
Object.defineProperty(exports, "findIngredients", { enumerable: true, get: function () { return find_ingredients_1.findIngredients; } });
var audit_missing_ingredients_1 = require("./audit-missing-ingredients");
Object.defineProperty(exports, "auditMissingIngredients", { enumerable: true, get: function () { return audit_missing_ingredients_1.auditMissingIngredients; } });
var recognize_food_1 = require("./recognize-food");
Object.defineProperty(exports, "recognizeFood", { enumerable: true, get: function () { return recognize_food_1.recognizeFood; } });
var scan_product_complete_1 = require("./scan-product-complete");
Object.defineProperty(exports, "scanProductComplete", { enumerable: true, get: function () { return scan_product_complete_1.scanProductComplete; } });
var infer_meal_ingredients_1 = require("./infer-meal-ingredients");
Object.defineProperty(exports, "inferMealIngredients", { enumerable: true, get: function () { return infer_meal_ingredients_1.inferMealIngredients; } });
var delete_generic_foods_1 = require("./delete-generic-foods");
Object.defineProperty(exports, "deleteGenericFoods", { enumerable: true, get: function () { return delete_generic_foods_1.deleteGenericFoods; } });
var search_generic_olive_oil_1 = require("./search-generic-olive-oil");
Object.defineProperty(exports, "searchGenericOliveOil", { enumerable: true, get: function () { return search_generic_olive_oil_1.searchGenericOliveOil; } });
var delete_specific_item_1 = require("./delete-specific-item");
Object.defineProperty(exports, "deleteSpecificItem", { enumerable: true, get: function () { return delete_specific_item_1.deleteSpecificItem; } });
// Algolia integration (auto-sync on document write + manual sync functions)
var algolia_sync_1 = require("./algolia-sync");
Object.defineProperty(exports, "syncVerifiedFoodToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncVerifiedFoodToAlgolia; } });
Object.defineProperty(exports, "syncFoodToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncFoodToAlgolia; } });
Object.defineProperty(exports, "syncManualFoodToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncManualFoodToAlgolia; } });
Object.defineProperty(exports, "syncUserAddedFoodToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncUserAddedFoodToAlgolia; } });
Object.defineProperty(exports, "syncAIEnhancedFoodToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncAIEnhancedFoodToAlgolia; } });
Object.defineProperty(exports, "syncAIManuallyAddedFoodToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncAIManuallyAddedFoodToAlgolia; } });
Object.defineProperty(exports, "syncTescoProductToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncTescoProductToAlgolia; } });
Object.defineProperty(exports, "syncUKFoodsCleanedToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncUKFoodsCleanedToAlgolia; } });
Object.defineProperty(exports, "bulkImportFoodsToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.bulkImportFoodsToAlgolia; } });
Object.defineProperty(exports, "searchFoodsAlgolia", { enumerable: true, get: function () { return algolia_sync_1.searchFoodsAlgolia; } });
Object.defineProperty(exports, "configureAlgoliaIndices", { enumerable: true, get: function () { return algolia_sync_1.configureAlgoliaIndices; } });
Object.defineProperty(exports, "syncNewDatabasesToAlgolia", { enumerable: true, get: function () { return algolia_sync_1.syncNewDatabasesToAlgolia; } });
// Algolia reverse sync (Algolia -> Firebase)
var algolia_reverse_sync_1 = require("./algolia-reverse-sync");
Object.defineProperty(exports, "checkAlgoliaFirebaseSync", { enumerable: true, get: function () { return algolia_reverse_sync_1.checkAlgoliaFirebaseSync; } });
Object.defineProperty(exports, "syncAlgoliaToFirebase", { enumerable: true, get: function () { return algolia_reverse_sync_1.syncAlgoliaToFirebase; } });
Object.defineProperty(exports, "getAlgoliaIndexStats", { enumerable: true, get: function () { return algolia_reverse_sync_1.getAlgoliaIndexStats; } });
// Generic foods enhancement (OpenFoodFacts data)
var enhance_generic_foods_1 = require("./enhance-generic-foods");
Object.defineProperty(exports, "enhanceGenericFoods", { enumerable: true, get: function () { return enhance_generic_foods_1.enhanceGenericFoods; } });
Object.defineProperty(exports, "getEnhancementStats", { enumerable: true, get: function () { return enhance_generic_foods_1.getEnhancementStats; } });
// McCance & Widdowson UK Food Composition Database
var import_mccance_widdowson_1 = require("./import-mccance-widdowson");
Object.defineProperty(exports, "importMcCanceWiddowson", { enumerable: true, get: function () { return import_mccance_widdowson_1.importMcCanceWiddowson; } });
Object.defineProperty(exports, "getGenericDatabaseStats", { enumerable: true, get: function () { return import_mccance_widdowson_1.getGenericDatabaseStats; } });
Object.defineProperty(exports, "syncGenericDatabaseToAlgolia", { enumerable: true, get: function () { return import_mccance_widdowson_1.syncGenericDatabaseToAlgolia; } });
Object.defineProperty(exports, "cleanupGenericDatabase", { enumerable: true, get: function () { return import_mccance_widdowson_1.cleanupGenericDatabase; } });
Object.defineProperty(exports, "clearGenericDatabase", { enumerable: true, get: function () { return import_mccance_widdowson_1.clearGenericDatabase; } });
// Consumer-friendly foods database (built from MW data with everyday serving sizes)
var import_consumer_foods_1 = require("./import-consumer-foods");
Object.defineProperty(exports, "importConsumerFoods", { enumerable: true, get: function () { return import_consumer_foods_1.importConsumerFoods; } });
Object.defineProperty(exports, "getConsumerFoodsStats", { enumerable: true, get: function () { return import_consumer_foods_1.getConsumerFoodsStats; } });
Object.defineProperty(exports, "syncConsumerFoodsToAlgolia", { enumerable: true, get: function () { return import_consumer_foods_1.syncConsumerFoodsToAlgolia; } });
Object.defineProperty(exports, "clearConsumerFoods", { enumerable: true, get: function () { return import_consumer_foods_1.clearConsumerFoods; } });
Object.defineProperty(exports, "consolidateConsumerFoods", { enumerable: true, get: function () { return import_consumer_foods_1.consolidateConsumerFoods; } });
// Algolia synonyms and query rules
var food_synonyms_1 = require("./food-synonyms");
Object.defineProperty(exports, "syncSynonymsToAlgolia", { enumerable: true, get: function () { return food_synonyms_1.syncSynonymsToAlgolia; } });
Object.defineProperty(exports, "getSynonymStats", { enumerable: true, get: function () { return food_synonyms_1.getSynonymStats; } });
Object.defineProperty(exports, "clearSynonymsFromAlgolia", { enumerable: true, get: function () { return food_synonyms_1.clearSynonymsFromAlgolia; } });
var algolia_query_rules_1 = require("./algolia-query-rules");
Object.defineProperty(exports, "configureQueryRules", { enumerable: true, get: function () { return algolia_query_rules_1.configureQueryRules; } });
Object.defineProperty(exports, "getQueryRulesStats", { enumerable: true, get: function () { return algolia_query_rules_1.getQueryRulesStats; } });
Object.defineProperty(exports, "clearQueryRules", { enumerable: true, get: function () { return algolia_query_rules_1.clearQueryRules; } });
// Mailchimp email marketing sync
var mailchimp_sync_1 = require("./mailchimp-sync");
Object.defineProperty(exports, "syncEmailConsentToMailchimp", { enumerable: true, get: function () { return mailchimp_sync_1.syncEmailConsentToMailchimp; } });
Object.defineProperty(exports, "syncAllEmailConsentsToMailchimp", { enumerable: true, get: function () { return mailchimp_sync_1.syncAllEmailConsentsToMailchimp; } });
// Database scanning and batch operations
var scan_database_1 = require("./scan-database");
Object.defineProperty(exports, "scanDatabaseIssues", { enumerable: true, get: function () { return scan_database_1.scanDatabaseIssues; } });
Object.defineProperty(exports, "batchUpdateFoods", { enumerable: true, get: function () { return scan_database_1.batchUpdateFoods; } });
Object.defineProperty(exports, "batchUpdateFoodsWithFirebase", { enumerable: true, get: function () { return scan_database_1.batchUpdateFoodsWithFirebase; } });
Object.defineProperty(exports, "fixKjKcalCombinedCalories", { enumerable: true, get: function () { return scan_database_1.fixKjKcalCombinedCalories; } });
Object.defineProperty(exports, "fixSimpleIngredients", { enumerable: true, get: function () { return scan_database_1.fixSimpleIngredients; } });
Object.defineProperty(exports, "fixHtmlCode", { enumerable: true, get: function () { return scan_database_1.fixHtmlCode; } });
Object.defineProperty(exports, "rescanProducts", { enumerable: true, get: function () { return scan_database_1.rescanProducts; } });
// UK Data Cleansing - Google Discovery and Extraction
var uk_discovery_1 = require("./uk-discovery");
Object.defineProperty(exports, "discoverUKProductPage", { enumerable: true, get: function () { return uk_discovery_1.discoverUKProductPage; } });
Object.defineProperty(exports, "generateManualSearchLinks", { enumerable: true, get: function () { return uk_discovery_1.generateManualSearchLinks; } });
var uk_extractor_1 = require("./uk-extractor");
Object.defineProperty(exports, "extractUKProductData", { enumerable: true, get: function () { return uk_extractor_1.extractUKProductData; } });
Object.defineProperty(exports, "extractWithPuppeteer", { enumerable: true, get: function () { return uk_extractor_1.extractWithPuppeteer; } });
Object.defineProperty(exports, "lookupTescoProduct", { enumerable: true, get: function () { return uk_extractor_1.lookupTescoProduct; } });
// Tesco Database Builder - builds comprehensive UK food database from Tesco API
var tesco_database_builder_1 = require("./tesco-database-builder");
Object.defineProperty(exports, "getTescoBuildProgress", { enumerable: true, get: function () { return tesco_database_builder_1.getTescoBuildProgress; } });
Object.defineProperty(exports, "startTescoBuild", { enumerable: true, get: function () { return tesco_database_builder_1.startTescoBuild; } });
Object.defineProperty(exports, "pauseTescoBuild", { enumerable: true, get: function () { return tesco_database_builder_1.pauseTescoBuild; } });
Object.defineProperty(exports, "stopTescoBuild", { enumerable: true, get: function () { return tesco_database_builder_1.stopTescoBuild; } });
Object.defineProperty(exports, "resetTescoDatabase", { enumerable: true, get: function () { return tesco_database_builder_1.resetTescoDatabase; } });
Object.defineProperty(exports, "getTescoDatabaseStats", { enumerable: true, get: function () { return tesco_database_builder_1.getTescoDatabaseStats; } });
Object.defineProperty(exports, "configureTescoAlgoliaIndex", { enumerable: true, get: function () { return tesco_database_builder_1.configureTescoAlgoliaIndex; } });
Object.defineProperty(exports, "syncTescoToAlgolia", { enumerable: true, get: function () { return tesco_database_builder_1.syncTescoToAlgolia; } });
Object.defineProperty(exports, "scheduledTescoBuild", { enumerable: true, get: function () { return tesco_database_builder_1.scheduledTescoBuild; } });
Object.defineProperty(exports, "cleanupTescoDatabase", { enumerable: true, get: function () { return tesco_database_builder_1.cleanupTescoDatabase; } });
// AI Food Categorization - categorizes foods for intelligent serving size suggestions
var categorize_foods_1 = require("./categorize-foods");
Object.defineProperty(exports, "categorizeFoods", { enumerable: true, get: function () { return categorize_foods_1.categorizeFoods; } });
Object.defineProperty(exports, "categorizeFoodsFromDatabase", { enumerable: true, get: function () { return categorize_foods_1.categorizeFoodsFromDatabase; } });
Object.defineProperty(exports, "getCategorizeStats", { enumerable: true, get: function () { return categorize_foods_1.getCategorizeStats; } });
Object.defineProperty(exports, "updateFoodCategory", { enumerable: true, get: function () { return categorize_foods_1.updateFoodCategory; } });
Object.defineProperty(exports, "getCategories", { enumerable: true, get: function () { return categorize_foods_1.getCategories; } });
Object.defineProperty(exports, "getFoodsForCategorization", { enumerable: true, get: function () { return categorize_foods_1.getFoodsForCategorization; } });
Object.defineProperty(exports, "getCategorizationProgress", { enumerable: true, get: function () { return categorize_foods_1.getCategorizationProgress; } });
Object.defineProperty(exports, "resetCategorizationProgress", { enumerable: true, get: function () { return categorize_foods_1.resetCategorizationProgress; } });
Object.defineProperty(exports, "fixCustomCategoryServingSizes", { enumerable: true, get: function () { return categorize_foods_1.fixCustomCategoryServingSizes; } });
Object.defineProperty(exports, "fixFoodServingSizes", { enumerable: true, get: function () { return categorize_foods_1.fixFoodServingSizes; } });
Object.defineProperty(exports, "batchSaveFoodCategories", { enumerable: true, get: function () { return categorize_foods_1.batchSaveFoodCategories; } });
// AI Data Validation - validates and cleans food data using AI knowledge
var validate_foods_1 = require("./validate-foods");
Object.defineProperty(exports, "validateFoodsFromDatabase", { enumerable: true, get: function () { return validate_foods_1.validateFoodsFromDatabase; } });
Object.defineProperty(exports, "getValidationStats", { enumerable: true, get: function () { return validate_foods_1.getValidationStats; } });
Object.defineProperty(exports, "getValidationProgress", { enumerable: true, get: function () { return validate_foods_1.getValidationProgress; } });
Object.defineProperty(exports, "resetValidationProgress", { enumerable: true, get: function () { return validate_foods_1.resetValidationProgress; } });
Object.defineProperty(exports, "getFoodsForValidation", { enumerable: true, get: function () { return validate_foods_1.getFoodsForValidation; } });
Object.defineProperty(exports, "getMarkedForDeletion", { enumerable: true, get: function () { return validate_foods_1.getMarkedForDeletion; } });
Object.defineProperty(exports, "deleteMarkedItems", { enumerable: true, get: function () { return validate_foods_1.deleteMarkedItems; } });
Object.defineProperty(exports, "unmarkForDeletion", { enumerable: true, get: function () { return validate_foods_1.unmarkForDeletion; } });
Object.defineProperty(exports, "clearMarkedForDeletion", { enumerable: true, get: function () { return validate_foods_1.clearMarkedForDeletion; } });
// Food image upload and processing
var upload_food_image_1 = require("./upload-food-image");
Object.defineProperty(exports, "uploadFoodImage", { enumerable: true, get: function () { return upload_food_image_1.uploadFoodImage; } });
Object.defineProperty(exports, "batchUploadFoodImages", { enumerable: true, get: function () { return upload_food_image_1.batchUploadFoodImages; } });
// Nutrition data update
var update_food_nutrition_1 = require("./update-food-nutrition");
Object.defineProperty(exports, "updateFoodNutrition", { enumerable: true, get: function () { return update_food_nutrition_1.updateFoodNutrition; } });
// Tesco image quality filtering
var filter_tesco_images_1 = require("./filter-tesco-images");
Object.defineProperty(exports, "filterTescoImages", { enumerable: true, get: function () { return filter_tesco_images_1.filterTescoImages; } });
Object.defineProperty(exports, "getTescoImageStats", { enumerable: true, get: function () { return filter_tesco_images_1.getTescoImageStats; } });
var sync_tesco_quality_1 = require("./sync-tesco-quality");
Object.defineProperty(exports, "syncTescoImageQuality", { enumerable: true, get: function () { return sync_tesco_quality_1.syncTescoImageQuality; } });
// Master database sync to Algolia
var sync_master_database_1 = require("./sync-master-database");
Object.defineProperty(exports, "clearAlgoliaIndex", { enumerable: true, get: function () { return sync_master_database_1.clearAlgoliaIndex; } });
Object.defineProperty(exports, "syncMasterDatabaseToAlgolia", { enumerable: true, get: function () { return sync_master_database_1.syncMasterDatabaseToAlgolia; } });
Object.defineProperty(exports, "getMasterDatabaseStats", { enumerable: true, get: function () { return sync_master_database_1.getMasterDatabaseStats; } });
// Local database sync - version tracking and delta sync for iOS offline database
var database_sync_1 = require("./database-sync");
Object.defineProperty(exports, "getCurrentDatabaseVersion", { enumerable: true, get: function () { return database_sync_1.getCurrentDatabaseVersion; } });
Object.defineProperty(exports, "getFoodDatabaseDelta", { enumerable: true, get: function () { return database_sync_1.getFoodDatabaseDelta; } });
Object.defineProperty(exports, "recordFoodUpdate", { enumerable: true, get: function () { return database_sync_1.recordFoodUpdate; } });
Object.defineProperty(exports, "initializeDatabaseVersion", { enumerable: true, get: function () { return database_sync_1.initializeDatabaseVersion; } });
Object.defineProperty(exports, "getSyncStats", { enumerable: true, get: function () { return database_sync_1.getSyncStats; } });
Object.defineProperty(exports, "cleanupOldFoodUpdates", { enumerable: true, get: function () { return database_sync_1.cleanupOldFoodUpdates; } });
//# sourceMappingURL=index.js.map