"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.standardizeIngredients = exports.replaceAllFoods = exports.processIngredientText = exports.detectLiveText = exports.testCors = exports.updateCleansedFoodStatus = exports.emergencyCleanCleansedFoods = exports.updateCleansedFood = exports.deleteCleansedFood = exports.exportCleansedFoods = exports.getCleansedFoods = exports.analyzeAndCleanFoods = exports.getAllFoods = exports.getNutrientSuggestions = exports.importGenericFoods = exports.searchFoodsWithMicronutrients = exports.extractIngredientsWithAI = exports.analyzeAdditivesEnhanced = exports.getContextualNutritionScore = exports.getUserAnalytics = exports.deleteUsers = exports.updateUser = exports.addUser = exports.getUsers = exports.getAnalyticsData = exports.getOverviewStats = exports.updateServingSizes = exports.fixExistingFoodsVerification = exports.resetAllFoodsToInitial = exports.resetAdminManualFoods = exports.moveFoodBetweenCollections = exports.deleteVerifiedFoods = exports.updateVerifiedFood = exports.addVerifiedFood = exports.searchFoodsByCollection = exports.getFoodDetails = exports.searchFoodsWeb = exports.fastSearchFoods = exports.searchFoodByBarcode = exports.searchCleansedFoods = exports.searchFoods = exports.addVerifiedFoodComplete = void 0;
const admin = require("firebase-admin");
// Initialize Firebase Admin
if (!admin.apps.length) {
    admin.initializeApp();
}
// Export the essential functions
var efficient_import_1 = require("./efficient-import");
Object.defineProperty(exports, "addVerifiedFoodComplete", { enumerable: true, get: function () { return efficient_import_1.addVerifiedFoodComplete; } });
var search_foods_1 = require("./search-foods");
Object.defineProperty(exports, "searchFoods", { enumerable: true, get: function () { return search_foods_1.searchFoods; } });
var search_cleansed_foods_1 = require("./search-cleansed-foods");
Object.defineProperty(exports, "searchCleansedFoods", { enumerable: true, get: function () { return search_cleansed_foods_1.searchCleansedFoods; } });
var search_food_by_barcode_1 = require("./search-food-by-barcode");
Object.defineProperty(exports, "searchFoodByBarcode", { enumerable: true, get: function () { return search_food_by_barcode_1.searchFoodByBarcode; } });
var fast_search_1 = require("./fast-search");
Object.defineProperty(exports, "fastSearchFoods", { enumerable: true, get: function () { return fast_search_1.fastSearchFoods; } });
var search_foods_web_1 = require("./search-foods-web");
Object.defineProperty(exports, "searchFoodsWeb", { enumerable: true, get: function () { return search_foods_web_1.searchFoodsWeb; } });
var food_details_1 = require("./food-details");
Object.defineProperty(exports, "getFoodDetails", { enumerable: true, get: function () { return food_details_1.getFoodDetails; } });
var search_foods_by_collection_1 = require("./search-foods-by-collection");
Object.defineProperty(exports, "searchFoodsByCollection", { enumerable: true, get: function () { return search_foods_by_collection_1.searchFoodsByCollection; } });
var food_management_1 = require("./food-management");
Object.defineProperty(exports, "addVerifiedFood", { enumerable: true, get: function () { return food_management_1.addVerifiedFood; } });
Object.defineProperty(exports, "updateVerifiedFood", { enumerable: true, get: function () { return food_management_1.updateVerifiedFood; } });
Object.defineProperty(exports, "deleteVerifiedFoods", { enumerable: true, get: function () { return food_management_1.deleteVerifiedFoods; } });
Object.defineProperty(exports, "moveFoodBetweenCollections", { enumerable: true, get: function () { return food_management_1.moveFoodBetweenCollections; } });
Object.defineProperty(exports, "resetAdminManualFoods", { enumerable: true, get: function () { return food_management_1.resetAdminManualFoods; } });
Object.defineProperty(exports, "resetAllFoodsToInitial", { enumerable: true, get: function () { return food_management_1.resetAllFoodsToInitial; } });
Object.defineProperty(exports, "fixExistingFoodsVerification", { enumerable: true, get: function () { return food_management_1.fixExistingFoodsVerification; } });
Object.defineProperty(exports, "updateServingSizes", { enumerable: true, get: function () { return food_management_1.updateServingSizes; } });
var analytics_1 = require("./analytics");
Object.defineProperty(exports, "getOverviewStats", { enumerable: true, get: function () { return analytics_1.getOverviewStats; } });
Object.defineProperty(exports, "getAnalyticsData", { enumerable: true, get: function () { return analytics_1.getAnalyticsData; } });
var user_management_1 = require("./user-management");
Object.defineProperty(exports, "getUsers", { enumerable: true, get: function () { return user_management_1.getUsers; } });
Object.defineProperty(exports, "addUser", { enumerable: true, get: function () { return user_management_1.addUser; } });
Object.defineProperty(exports, "updateUser", { enumerable: true, get: function () { return user_management_1.updateUser; } });
Object.defineProperty(exports, "deleteUsers", { enumerable: true, get: function () { return user_management_1.deleteUsers; } });
Object.defineProperty(exports, "getUserAnalytics", { enumerable: true, get: function () { return user_management_1.getUserAnalytics; } });
var contextual_nutrition_1 = require("./contextual-nutrition");
Object.defineProperty(exports, "getContextualNutritionScore", { enumerable: true, get: function () { return contextual_nutrition_1.getContextualNutritionScore; } });
var additive_analyzer_enhanced_1 = require("./additive-analyzer-enhanced");
Object.defineProperty(exports, "analyzeAdditivesEnhanced", { enumerable: true, get: function () { return additive_analyzer_enhanced_1.analyzeAdditivesEnhanced; } });
var intelligent_ingredient_extractor_1 = require("./intelligent-ingredient-extractor");
Object.defineProperty(exports, "extractIngredientsWithAI", { enumerable: true, get: function () { return intelligent_ingredient_extractor_1.extractIngredientsWithAI; } });
var enhanced_micronutrient_search_1 = require("./enhanced-micronutrient-search");
Object.defineProperty(exports, "searchFoodsWithMicronutrients", { enumerable: true, get: function () { return enhanced_micronutrient_search_1.searchFoodsWithMicronutrients; } });
var import_generic_foods_1 = require("./import-generic-foods");
Object.defineProperty(exports, "importGenericFoods", { enumerable: true, get: function () { return import_generic_foods_1.importGenericFoods; } });
Object.defineProperty(exports, "getNutrientSuggestions", { enumerable: true, get: function () { return import_generic_foods_1.getNutrientSuggestions; } });
var get_all_foods_1 = require("./get-all-foods");
Object.defineProperty(exports, "getAllFoods", { enumerable: true, get: function () { return get_all_foods_1.getAllFoods; } });
var ai_food_cleaner_1 = require("./ai-food-cleaner");
Object.defineProperty(exports, "analyzeAndCleanFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.analyzeAndCleanFoods; } });
Object.defineProperty(exports, "getCleansedFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.getCleansedFoods; } });
Object.defineProperty(exports, "exportCleansedFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.exportCleansedFoods; } });
Object.defineProperty(exports, "deleteCleansedFood", { enumerable: true, get: function () { return ai_food_cleaner_1.deleteCleansedFood; } });
Object.defineProperty(exports, "updateCleansedFood", { enumerable: true, get: function () { return ai_food_cleaner_1.updateCleansedFood; } });
Object.defineProperty(exports, "emergencyCleanCleansedFoods", { enumerable: true, get: function () { return ai_food_cleaner_1.emergencyCleanCleansedFoods; } });
Object.defineProperty(exports, "updateCleansedFoodStatus", { enumerable: true, get: function () { return ai_food_cleaner_1.updateCleansedFoodStatus; } });
var test_cors_1 = require("./test-cors");
Object.defineProperty(exports, "testCors", { enumerable: true, get: function () { return test_cors_1.testCors; } });
var detect_live_text_1 = require("./detect-live-text");
Object.defineProperty(exports, "detectLiveText", { enumerable: true, get: function () { return detect_live_text_1.detectLiveText; } });
var process_ingredient_text_1 = require("./process-ingredient-text");
Object.defineProperty(exports, "processIngredientText", { enumerable: true, get: function () { return process_ingredient_text_1.processIngredientText; } });
var replace_foods_database_1 = require("./replace-foods-database");
Object.defineProperty(exports, "replaceAllFoods", { enumerable: true, get: function () { return replace_foods_database_1.replaceAllFoods; } });
var standardize_ingredients_1 = require("./standardize-ingredients");
Object.defineProperty(exports, "standardizeIngredients", { enumerable: true, get: function () { return standardize_ingredients_1.standardizeIngredients; } });
//# sourceMappingURL=index.js.map